[general]
id = "cs1-ff00_0_110-1"
config_dir = "gen/ASff00_0_110"
reconnect_to_dispatcher = true

[trust_db]
connection = "gen-cache/cs1-ff00_0_110-1.trust.db"

[beacon_db]
connection = "gen-cache/cs1-ff00_0_110-1.beacon.db"

[path_db]
connection = "gen-cache/cs1-ff00_0_110-1.path.db"

[tracing]

[metrics]
prometheus = "127.0.0.1:30452"

[api]
addr = "127.0.0.1:31152"

[features]

[ca]
mode = "in-process"

[log.console]
level = "info"

[drkey.level1_db]
connection = "gen-cache/cs1-ff00_0_110-1.drkey_level1.db"

[drkey.secret_value_db]
connection = "gen-cache/cs1-ff00_0_110-1.secret_value.db"
