local_address = "16-ffaa:0:1006,172.31.27.239"
scion_daemon_address = "127.0.0.1:30255"

phc_reference_clocks = ["/dev/ptp0"]
scion_peer_clocks = ["16-ffaa:0:1006,172.31.18.72:10123","16-ffaa:0:1006,172.31.25.230:10123","16-ffaa:0:1006,172.31.22.172:10123"]

ntske_cert_file = "./tls.crt"
ntske_key_file = "./tls.key"
ntske_server_name = "localhost"

clock_drift = 0.000015

reference_clock_impact = 1.1
peer_clock_impact = 2.25
peer_clock_cutoff = 0.000005
sync_timeout = 0.125
sync_interval = 0.25
