local_address = "1-ff00:0:110,{{.ASff00_0_110_TS_IP_0}}:10123"
daemon_address = "127.0.0.1:30255"

ntp_reference_clocks = ["0-0,{{.CHRONY_IP_0}}:123"]

ntske_cert_file = "gen/tls.crt"
ntske_key_file = "gen/tls.key"
ntske_server_name = "localhost"
